### ISSUE TITLE
Updated rewrap, and now it's wrapping one particular comment at the wrong column

### ISSUE THREAD

**Issue by nullstyle** [stkb/vscode-rewrap#13] opened 2016-09-29 15:38 UTC
Here's the improper result (stripped down to the smallest repro):

``` golang
package main

const (
    // PayoutStatusStarted represents the value of a
    // payout row's `status` column. It represents a
    // payout that has been validated and started but has
    // not yet been completed.
    PayoutStatusStarted = "started"

    PayoutStatusSuccess = "success"
)
```

Expected:

``` golang
package main

const (
    // PayoutStatusStarted represents the value of a payout row's `status` column.
    // It represents a payout that has been validated and started but has not yet
    // been completed.
    PayoutStatusStarted = "started"

    PayoutStatusSuccess = "success"
)
```

Now, here's the really weird part:  If the file is not saved to disk, rewrap works properly...  I can create a new empty file, set the syntax to "Go", paste that code and rewrap the comment and it properly wraps to 80 columns.  If I then simply save that file to the disk, rewrap starts improperly wrapping the comment to ~55 columns.

**Comment by stkb** [comment] 2016-09-29 17:15
Hmm, I can't repro on my machine (Windows 10); it's always working fine for me. So here's a list of troubleshooting questions (sorry if some of these sound stupid, I'm stabbing in the dark a bit here).
* What OS are you on, and are you using rewrap v0.6.2 on vscode 1.5.3?
* Is it just a standard .go file or some other extension?
* Does the bug always happen no matter where you save the file? (Are sure there's not a local settings.json file in the project with a different wrapping column?) 
* Are there any errors in the developer console? (Help -> Toggle Developer Tools -> Console Tab)
 * (Ignore warnings: "Edits from command rewrap.rewrapComment were not applied"; it's some bug in vscode that's existed for ages)
* Tried uninstalling/reinstalling the extension?
* Does it still fail in a .go file that has just an unindented comment block, eg this?
```
// Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod 
// tempor incididunt ut labore et dolore 
// magna aliqua. Ut enim ad minim veniam, 
// quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
```

Failing all that, could you attach a file that's not working for you?

**Comment by nullstyle** [comment] 2016-09-29 17:30
- yep, 0.6.2 and 1.5.3
- yep, just a standard go file
- I've tested inside the GOPATH and outside the GOPATH, it happens in both situations
- I'm getting warnings on the devtools when running rewrap:
```
mainThreadEditorsTracker.ts:325 Model has changed in the meantime!
threadService.ts:217 [Extension Host] Edits from command rewrap.rewrapComment were not applied. 
```
- not yet
----

Regarding your last question, while testing I noticed something:

```golang
// Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
// tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
// quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
// consequat.
type foo struct {
	// Lorem ipsum dolor sit amet, consectetur adipiscing
	// elit, sed do eiusmod tempor incididunt ut labore
	// et dolore magna aliqua. Ut enim ad minim veniam,
	// quis nostrud exercitation ullamco laboris nisi ut
	// aliquip ex ea commodo consequat.
	foo string
}
```

Both comments are rewrapped... notice that the nested comment was improperly rewrapped.

----

As far as attaching the file... the first block I posted in the bug report is the complete file.

**Comment by nullstyle** [comment] 2016-09-29 17:43
yep, still broken after an uninstall/reinstall of the extension.

**Comment by stkb** [comment] 2016-09-29 19:57
Thanks. The reason I asked for a file was so I could see exactly where whitespace was located, if spaces or tabs were used, line endings etc.

Anyway, since you're using Go, I assume you're using tabs? I can now sort of repro the bug. Rewrap checks the user's "editor.tabSize" setting to calulate the indent size where tabs are used. If the value it gets there is not a number, then the results are exactly as you've seen (wrapping around column 55).

However I can't find any circumstance where vscode doesn't return a number for that setting (if the user has set it as something weird, vscode seems to give a default value of 4).

Could you maybe post the contents of your user `settings.json` file?

Meanwhile I'll work on a special version of the extension that has extra logging.

Also pinging @peterbourgon (also a Go user I think) just wondering if everything's working for you?

**Comment by nullstyle** [comment] 2016-09-29 20:03
Here's my settings:

```
{
  "editor.tabSize": 2,
  "editor.wrappingColumn": 80,
  "editor.wrappingIndent": "indent",
  "editor.renderIndentGuides": true,
  "window.zoomLevel": 0.5,
  "eslint.enable": false
}
```

Here's a gist to the a file I've repro'd the bug against in my environment:  https://gist.github.com/nullstyle/41f202676b4dfd7705e3249522c680f7

**Comment by peterbourgon** [comment] 2016-09-29 20:05
Hey! Mac OS X 10.11 El Capitan, VS Code 1.5.3, Rewrap 0.6.2, settings:

```json
// Place your settings in this file to overwrite the default settings
{
	"editor.fontFamily": "mononoki",
	"editor.renderWhitespace": true,
	"explorer.workingFiles.maxVisible": 999,
	"files.trimTrailingWhitespace": true,
	"go.formatOnSave": true,
	"go.formatTool": "goimports",
	"go.gopath": "/Users/peter",
	"go.useCodeSnippetsOnFunctionSuggest": false,
	"rewrap.wrappingColumn": 80
}
```

Can't reproduce—wrapping works OK for me with this file. [Here's a video](https://dl.dropboxusercontent.com/u/1061416/wrap.mov).

**Comment by nullstyle** [comment] 2016-09-29 20:06
_interesting:_  I just re-saved my settings.json (was fucking around with tabSize) and the issue went away.  Perhaps this is an interaction between your package and https://github.com/shanalikhan/code-settings-sync

**Comment by stkb** [comment] 2016-09-30 14:51
@peterbourgon Thanks very much for the detailed post!

@nullstyle Thanks too and glad you could fix it. Rewrap [asks vscode for the tab size](http://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditorOptions), which in turn looks at the `settings.json` file. It looks like somehow the state of your settings file was causing vscode to give an invalid value. Maybe it was caused by the settings sync extension, I don't know, but it's weird and I can't replicate it.

Anyway I've added some code to sanitize the received values for tabSize (and wrappingColumn). It writes a warning to the console if something's wrong and use a default value of 4. This will be in the next release.

**Comment by nullstyle** [comment] 2016-09-30 15:17
@stkb Sounds like a plan.  Thanks so much for your help!  your package was one of the few that let me finally switch away from atom... it's central to documenting my code and would be painful without it.  Thanks!

**Closed** 2016-11-04 15:24 UTC
